#' dl_sanity_check()
#'
#' Helper function to check data_list
#'
#' @param data_list a datalist as generated by import_NBDA_STb or import_user_STb
#'
#' @return NULL, just print sanity check
dl_sanity_check <- function(data_list) {
    line <- paste0(
        "\u2591\u2592\u2593\u2588\u25BA\u2500\u2550",
        " Sanity check ",
        "\u2550\u2500\u25C4\u2588\u2593\u2592\u2591"
    )

    message(paste(
        line,
        "User provided data about:",
        paste(data_list$P, "individuals across", data_list$K, "independent diffusions (trials)."),
        paste("There were", data_list$Q, "individuals in each trial."),
        paste("User supplied", length(data_list$network_names), "networks:", paste(data_list$network_names, collapse = ", ")),
        paste("ILV for asocial learning:", paste(data_list$ILVi_names, collapse = ", ")),
        paste("ILV for social learning:", paste(data_list$ILVs_names, collapse = ", ")),
        paste("multiplicative model ILV:", paste(data_list$ILVm_names, collapse = ", ")),
        "\U0001F914 Does that seem right to you?",
        sep = "\n"
    ))
}
