#' dl_sanity_check: private function to check data_list
#'
#' @param data_list a datalist as generated by import_NBDA_STb or import_user_STb
#'
#' @return Nothing, just print sanity check
dl_sanity_check <- function(data_list){
    message(paste(
        " !Sanity check! User provided data about:\n",
        data_list$P, "individuals across",
        data_list$K, "independent diffusions (trials).\n",
        "There were", data_list$Q, "individuals in each trial.\n",
        "User supplied", length(data_list$network_names), "networks:", paste(data_list$network_names, collapse = ", "), "\n",
        "ILV for asocial learning:", paste(data_list$ILVi_names, collapse = ", "), "\n",
        "ILV for social learning:", paste(data_list$ILVs_names, collapse = ", "), "\n",
        "multipliative model ILV:", paste(data_list$ILVm_names, collapse = ", "), "\n"
    ))
}
