#' dl_sanity_check()
#'
#' Helper function to check data_list
#'
#' @param data_list a datalist as generated by import_NBDA_STb or import_user_STb
#'
#' @return NULL, just print sanity check
#' @noRd
dl_sanity_check <- function(data_list) {
    line <- paste0(
        "\u2591\u2592\u2593\u2588\u25BA\u2500\u2550",
        " Sanity check ",
        "\u2550\u2500\u25C4\u2588\u2593\u2592\u2591"
    )

    message(paste(
        line,
        "User provided data about:",
        paste(data_list$P, "individuals across", data_list$K, "independent diffusions (trials)."),
        paste(data_list$N, "of", data_list$N + data_list$N_c, "individuals learned in trial", 1:length(data_list$N), collapse = "\n"),
        paste("User supplied", length(data_list$network_names), "networks:", paste(data_list$network_names, collapse = ", ")),
        paste("ILV for asocial learning:", paste(data_list$ILVi_names, collapse = ", ")),
        paste("ILV for social learning:", paste(data_list$ILVs_names, collapse = ", ")),
        paste("multiplicative model ILV:", paste(data_list$ILVm_names, collapse = ", ")),
        "\U0001F914 Does that seem right to you?",
        sep = "\n"
    ))
}

#' @noRd
array_to_edge_matrix <- function(net_obj, trial = NULL, time = NULL) {
    nd <- length(dim(net_obj))

    if (nd == 3) {
        draws <- dim(net_obj)[1]
        P <- dim(net_obj)[2]
    } else if (nd == 4) {
        draws <- dim(net_obj)[2]
        P <- dim(net_obj)[3]
    } else if (nd == 5) {
        draws <- dim(net_obj)[3]
        P <- dim(net_obj)[4]
    } else {
        stop("\U0001F614 User-supplied posterior network arrays must be 3D, 4D, or 5D.")
    }

    edge_mat <- matrix(NA_real_, nrow = draws, ncol = P * (P - 1))
    idx <- 1

    for (i_focal in 1:P) {
        for (i_other in 1:P) {
            if (i_focal != i_other) {
                if (nd == 3) {
                    edge_mat[, idx] <- net_obj[, i_focal, i_other]
                } else if (nd == 4) {
                    edge_mat[, idx] <- net_obj[trial, , i_focal, i_other]
                } else {
                    edge_mat[, idx] <- net_obj[trial, time, , i_focal, i_other]
                }
                idx <- idx + 1
            }
        }
    }

    edge_mat
}

get_external_edges <- function(net_obj) {
    if (inherits(net_obj, "bison_model")) {
        dyads <- if (net_obj$directed) {
            strsplit(net_obj$dyad_names, " -> ")
        } else {
            strsplit(net_obj$dyad_names, " <-> ")
        }

        dyad_matrix <- do.call(rbind, dyads)
        dyad_df <- data.frame(
            focal = as.integer(dyad_matrix[, 1]),
            other = as.integer(dyad_matrix[, 2]),
            stringsAsFactors = FALSE
        )

        edge_samples <- net_obj$edge_samples[, dyad_df$focal != dyad_df$other, drop = FALSE]
        dyad_df <- dyad_df[dyad_df$focal != dyad_df$other, ]

        return(list(
            edges = edge_samples,
            focal_ID = dyad_df$focal,
            other_ID = dyad_df$other
        ))
    }

    if (inherits(net_obj, "STRAND Results Object")) {
        ass_matrix <- net_obj$samples$predicted_network_sample
        draws <- dim(ass_matrix)[1]
        P <- dim(ass_matrix)[2]

        edge_mat <- matrix(NA_real_, nrow = draws, ncol = P * (P - 1))
        focal_ID <- other_ID <- integer(P * (P - 1))
        idx <- 1

        for (i_focal in 1:P) {
            for (i_other in 1:P) {
                if (i_focal != i_other) {
                    edge_mat[, idx] <- ass_matrix[, i_focal, i_other]
                    focal_ID[idx] <- i_focal
                    other_ID[idx] <- i_other
                    idx <- idx + 1
                }
            }
        }

        return(list(
            edges = qlogis(edge_mat),
            focal_ID = focal_ID,
            other_ID = other_ID
        ))
    }

    stop("\U0001F614 Unrecognized external posterior network object.")
}

#' @noRd
validate_posterior_array <- function(net_obj, network_index, K, T_max, P) {
    if (!inherits(net_obj, "array")) {
        return(invisible(NULL))
    }

    nd <- length(dim(net_obj))

    if (!nd %in% c(3, 4, 5)) {
        stop(
            "\U0001F614 User-supplied posterior network arrays must be 3D [draw, focal_ID, other_ID], ",
            "4D [trial, draw, focal_ID, other_ID], or ",
            "5D [trial, time, draw, focal_ID, other_ID]."
        )
    }

    expected_dim_order <- switch(as.character(nd),
        "3" = c("draw", "focal_ID", "other_ID"),
        "4" = c("trial", "draw", "focal_ID", "other_ID"),
        "5" = c("trial", "time", "draw", "focal_ID", "other_ID")
    )

    dim_names <- names(dimnames(net_obj))

    if (is.null(dim_names) || !identical(dim_names, expected_dim_order)) {
        stop(
            "\U0001F614 Posterior network array ", network_index,
            " must have named dimensions: ",
            paste(expected_dim_order, collapse = ", "), "."
        )
    }

    observed_dims <- dim(net_obj)

    expected_dims <- switch(as.character(nd),
        "3" = c(NA_integer_, P, P),
        "4" = c(K, NA_integer_, P, P),
        "5" = c(K, T_max, NA_integer_, P, P)
    )

    checked_dims <- switch(as.character(nd),
        "3" = c(2, 3),
        "4" = c(1, 3, 4),
        "5" = c(1, 2, 4, 5)
    )

    if (!all(observed_dims[checked_dims] == expected_dims[checked_dims])) {
        expected_label <- switch(as.character(nd),
            "3" = paste(c("draws", P, P), collapse = " x "),
            "4" = paste(c(K, "draws", P, P), collapse = " x "),
            "5" = paste(c(K, T_max, "draws", P, P), collapse = " x ")
        )

        stop(
            "\U0001F614 Posterior network array ", network_index,
            " has dimensions ", paste(observed_dims, collapse = " x "),
            ", but expected ", expected_label, "."
        )
    }

    draw_dim <- switch(as.character(nd),
        "3" = 1,
        "4" = 2,
        "5" = 3
    )

    if (observed_dims[draw_dim] < 2) {
        stop("\U0001F614 Posterior network arrays need at least 2 draws to estimate an edge covariance matrix.")
    }

    if (anyNA(net_obj)) {
        stop(
            "\U0001F614 Missing values detected in posterior network array ",
            network_index,
            ". Please provide every required posterior draw."
        )
    }

    invisible(NULL)
}

#' @noRd
get_full_dyad_ids <- function(P) {
    focal_ID <- other_ID <- integer(P * (P - 1))
    idx <- 1

    for (i_focal in 1:P) {
        for (i_other in 1:P) {
            if (i_focal != i_other) {
                focal_ID[idx] <- i_focal
                other_ID[idx] <- i_other
                idx <- idx + 1
            }
        }
    }

    list(focal_ID = focal_ID, other_ID = other_ID)
}
