# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib STbayes, .registration = TRUE
#' @export
fill_array <- function(A_array, dims, focal, other, time, value, net_idx, trial_idx, symmetric) {
    invisible(.Call(`_STbayes_fill_array`, A_array, dims, focal, other, time, value, net_idx, trial_idx, symmetric))
}

